minimum_pre_commit_version: "2.10.0"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --dont-order-by-type
  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black
        name: Format code (black)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v1.15.0"
    hooks:
      - id: "mypy"
        name: "Check type hints (mypy)"
        verbose: true
ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit.com hooks

      for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: []
  submodules: false
