minimum_pre_commit_version: "2.10.0"
repos:
  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
        name: Format code (black)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.4.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
        name: Lint code (flake8)
        additional_dependencies:
          - flake8>=3.8.4
          - flake8-broken-line>=0.3.0
          - flake8-bugbear>=20.11.1
          - flake8-builtins>=1.5.3
          - flake8-comprehensions>=3.3.1
          - flake8-import-order>=0.18.1
          - flake8-mutable>=1.2.0
          - flake8-pie>=0.6.1
          - flake8-quotes>=3.2.0
          - flake8-string-format>=0.3.0
          - flake8-tidy-imports>=4.2.1
          - pep8-naming>=0.11.1
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v0.812"
    hooks:
      - id: "mypy"
        name: "Check type hints (mypy)"
        verbose: true
